### ISSUE TITLE
Web Scraper: Meetup

### ISSUE THREAD

**Issue by mnich0ls** [mnich0ls/evee-sd#12]
Scrape events from: https://www.meetup.com/find/events/?allMeetups=true&radius=50&userFreeform=San+Diego%2C+CA&mcId=z92101&mcName=San+Diego%2C+CA&eventFilter=all

Events should be persisted to the `scraped_events` collection ([see Database](
https://github.com/mnich0ls/evee-sd/wiki/Database)) with the following metadata:

`source_url`: https://www.meetup.com
`date_scraped`: (the ISO 8601 timestamp for the time the event was pulled from the source site)
`status`: new

See [Event Attributes](https://github.com/mnich0ls/evee-sd/wiki/Event-Attributes) for the event attributes that should be scraped.

**Comment by jremi** [comment]
@mnich0ls please assign me to this task.

I just performed a preliminary initial integration into Meetups API. They have an endpoint resource that will provide what we need. There is no reason to webscrape this page (unless you really want that method)... since we can get the data directly from there API. The endpoint is `api.meetup.com/find/upcoming_events` 

Please take a look at this JSON response I just got for the San Diego area.
https://gist.github.com/jremi/6d0ae568790b5338e7034aebcd76dd9e

**Comment by mnich0ls** [comment]
Perfect. Please use the API instead.

**Comment by mnich0ls** [comment]
Whatever makes any task easier or faster is fair game to me.
